


export class HttpResponseData<T> {

  static RESPONSE_CODE = {
    OK:0,
    HTTP_ERROR:-1,
    UNKNOWN_ERROR:1,
    PARAM_ERROR:100,
    AUTH_TIMEOUT:101,
    PERMISSION_ERROR:102,
    USER_NOT_EXIST_ERROR:200,
    USERNAME_PASSWORD_ERROR:201,
    CHANGE_PASSWORD_ERROR:202,
    CLIENT_ADD_MULTI_ERROR:300,
    DELETE_USER_SELF_ERROR:400,
    ADD_USER_MULTI_ERROR:401
  }

  code:number
  msg:string
  data:T
}
